version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    depends_on:
      - mysql_mindshub
      - redis_mindshub

  mysql_mindshub:
    image: mysql:8.0
    container_name: mysql_mindshub
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mindshub
      MYSQL_USER: mindshub
      MYSQL_PASSWORD: mindshub1234
      MYSQL_ROOT_PASSWORD: mindshub1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin_mindshub:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_mindshub
    restart: unless-stopped
    depends_on:
      - mysql_mindshub
    environment:
      PMA_HOST: mysql_mindshub
      MYSQL_ROOT_PASSWORD: mindshub1234
    ports:
      - "8082:80"

  nginx_mindshub:
    image: nginx:latest
    container_name: nginx_mindshub
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  redis_mindshub:
    image: redis:latest
    container_name: redis_mindshub
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
